### ISSUE TITLE
Material-UI modal error after CRA build

### ISSUE THREAD

**Issue by engmagdy87** [preactjs/preact-compat#508]
this issue appears after build the app with react v16.4.1 with material-ui v1.4.0

![capture](https://user-images.githubusercontent.com/8473421/45394794-d00e0580-b632-11e8-9346-49fde999fb24.PNG)

**Comment by marvinhagemeister** [comment]
Do you have a code snippet or small repository where the bug can be reproduced?

**Comment by engmagdy87** [comment]
this error appear after build and run ```serve -s build``` command and as u see, the error location doesn't appear in console except ```Modal.js:58```

**Comment by marvinhagemeister** [comment]
@engmagdy87 Without any way to reproduce the issue I'm not sure how we can get to the bottom of it. The stacktrace of minified code is meaningless on it's own and nobody except you knows what's in `Modal.js`. We need more information about the issue you're experiencing.
