### ISSUE TITLE
Uncaught ReferenceError: h is not defined

### ISSUE THREAD

**Issue by rzschoch** [preactjs/preact-compat#541]
I try to omit the h imports for all my components while using a webpack/babel build process.

Following the preact documentation (https://preactjs.com/guide/v10/getting-started#integrating-into-an-existing-pipeline) for using preact with webpack I get this error:
`Uncaught ReferenceError: h is not defined`.

An old issue (https://github.com/preactjs/preact-compat/issues/161) mentions this solution that is also working for me:

```javascript
new webpack.ProvidePlugin({
  h: ['preact', 'h'],
})
```

Is there now a nicer solution to this problem?

**Comment by developit** [comment]
You can use the new [automatic JSX runtime](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#react-automatic-runtime-1) if you want to omit imports:

```js
// babel config
["@babel/plugin-transform-react-jsx"], {
  "runtime": "automatic",
  "importSource": "preact"
}]
```
