### ISSUE TITLE
README "without webpack" suggested usage doesn't work

### ISSUE THREAD

**Issue by ihenckel** [preactjs/preact-compat#544]
[These instructions](https://github.com/preactjs/preact-compat#use-without-webpackbrowserify) recommend:

```html
<script src="//unpkg.com/preact"></script>
<script src="//unpkg.com/prop-types/prop-types.min.js"></script>
<script src="//unpkg.com/preact-compat"></script>
<script>
    var React = preactCompat,
        ReactDOM = preactCompat;
    ReactDOM.render(<h1>Hello!</h1>, document.body);
</script>
```

However, this yields

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at index.js:56
    at preact-compat.js:4
    at preact-compat.js:5
(anonymous) @ index.js:56
(anonymous) @ preact-compat.js:4
(anonymous) @ preact-compat.js:5

Uncaught ReferenceError: preactCompat is not defined
```

See https://jsfiddle.net/jLf2mdpe/1/

**Comment by marvinhagemeister** [comment]
Mixing Preact 10 with `preact-compat` which was written for Preact 8.x won't work as suggested by the opening paragraph of the README:

> :rotating_light: Note: This module is for Preact 8.x and prior - Preact X includes compat by default. For Preact X, please uninstall preact-compat and replace your aliases with preact/compat.

In either case `unpkg` doesn't follow the resolution standard correctly (see: https://github.com/preactjs/preact/issues/2564 ) so you'll be better of with more modern CDNs that do. https://pika.dev or https://npm.reversehttp.com are both an excellent choice.

Example with the latter:

```html
<script type="module">
  import * as React from "https://npm.reversehttp.com/preact@10.4/compat";
  
  const app = React.createElement("div", null, "Hello World!");

  React.render(app, document.getElementById("app"));
</script>
```
